FROM node:20-alpine AS builder

RUN apk update && \
    apk add git wget curl bash openssl

LABEL version="2.2.1" description="Api to control whatsapp features through http requests." 
LABEL maintainer="Davidson Gomes" git="https://github.com/DavidsonGomes"
LABEL contact="contato@atendai.com"

WORKDIR /evolution

COPY ./package.json ./tsconfig.json ./

RUN npm install

COPY ./src ./src
COPY ./public ./public
COPY ./prisma ./prisma
ARG SERVER_URL
ARG DATABASE_ENABLED
ARG DATABASE_PROVIDER=postgresql
ARG DATABASE_CONNECTION_URI
ARG DATABASE_CONNECTION_CLIENT_NAME
ARG CACHE_REDIS_ENABLED
ARG CACHE_REDIS_URI
ARG AUTHENTICATION_API_KEY
ARG CONFIG_SESSION_PHONE_VERSION
ARG S3_ENABLED
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG S3_BUCKET
ARG S3_PORT
ARG S3_REGION
ARG S3_ENDPOINT
ARG S3_USE_SSL
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG RABBITMQ_URI
ARG DATABASE_SAVE_DATA_NEW_MESSAGE
ARG DATABASE_SAVE_MESSAGE_UPDATE
ARG DATABASE_SAVE_DATA_CONTACTS
ARG DATABASE_SAVE_DATA_CHATS
ARG DATABASE_SAVE_DATA_HISTORIC
ARG RABBITMQ_ENABLED
ARG RABBITMQ_EXCHANGE_NAME
ARG RABBITMQ_GLOBAL_ENABLED
ARG RABBITMQ_EVENTS_MESSAGES_SET
ARG RABBITMQ_EVENTS_MESSAGES_UPSERT
ARG RABBITMQ_EVENTS_MESSAGES_UPDATE
ARG RABBITMQ_EVENTS_MESSAGES_DELETE
ARG RABBITMQ_EVENTS_CHATS_SET
ARG RABBITMQ_EVENTS_CHATS_UPSERT
ARG RABBITMQ_EVENTS_CHATS_UPDATE
ARG RABBITMQ_EVENTS_CHATS_DELETE
ARG RABBITMQ_EVENTS_CONNECTION_UPDATE
ARG RABBITMQ_EVENTS_SEND_MESSAGE
ARG RABBITMQ_EVENTS_GROUPS_UPSERT
ARG RABBITMQ_EVENTS_INSTANCE_CREATE
ARG RABBITMQ_EVENTS_INSTANCE_DELETE
ARG RABBITMQ_EVENTS_QRCODE_UPDATED
ARG RABBITMQ_EVENTS_GROUPS_UPDATE
ARG RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE

ENV DOCKER_ENV=true \
    SERVER_URL=$SERVER_URL \
    DATABASE_ENABLED=$DATABASE_ENABLED \
    DATABASE_PROVIDER=${DATABASE_PROVIDER:-postgresql} \
    DATABASE_CONNECTION_URI=$DATABASE_CONNECTION_URI \
    DATABASE_CONNECTION_CLIENT_NAME=$DATABASE_CONNECTION_CLIENT_NAME \
    CACHE_REDIS_ENABLED=$CACHE_REDIS_ENABLED \
    CACHE_REDIS_URI=$CACHE_REDIS_URI \
    AUTHENTICATION_API_KEY=$AUTHENTICATION_API_KEY \
    CONFIG_SESSION_PHONE_VERSION=$CONFIG_SESSION_PHONE_VERSION \
    S3_ENABLED=$S3_ENABLED \
    S3_ACCESS_KEY=$S3_ACCESS_KEY \
    S3_SECRET_KEY=$S3_SECRET_KEY \
    S3_BUCKET=$S3_BUCKET \
    S3_PORT=$S3_PORT \
    S3_REGION=$S3_REGION \
    S3_ENDPOINT=$S3_ENDPOINT \
    S3_USE_SSL=$S3_USE_SSL \
    POSTGRES_USER=$POSTGRES_USER \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_DB=$POSTGRES_DB \
    RABBITMQ_URI=$RABBITMQ_URI \
    DATABASE_SAVE_DATA_NEW_MESSAGE=$DATABASE_SAVE_DATA_NEW_MESSAGE \
    DATABASE_SAVE_MESSAGE_UPDATE=$DATABASE_SAVE_MESSAGE_UPDATE \
    DATABASE_SAVE_DATA_CONTACTS=$DATABASE_SAVE_DATA_CONTACTS \
    DATABASE_SAVE_DATA_CHATS=$DATABASE_SAVE_DATA_CHATS \
    DATABASE_SAVE_DATA_HISTORIC=$DATABASE_SAVE_DATA_HISTORIC \
    RABBITMQ_ENABLED=$RABBITMQ_ENABLED \
    RABBITMQ_EXCHANGE_NAME=$RABBITMQ_EXCHANGE_NAME \
    RABBITMQ_GLOBAL_ENABLED=$RABBITMQ_GLOBAL_ENABLED \
    RABBITMQ_EVENTS_MESSAGES_SET=$RABBITMQ_EVENTS_MESSAGES_SET \
    RABBITMQ_EVENTS_MESSAGES_UPSERT=$RABBITMQ_EVENTS_MESSAGES_UPSERT \
    RABBITMQ_EVENTS_MESSAGES_UPDATE=$RABBITMQ_EVENTS_MESSAGES_UPDATE \
    RABBITMQ_EVENTS_MESSAGES_DELETE=$RABBITMQ_EVENTS_MESSAGES_DELETE \
    RABBITMQ_EVENTS_CHATS_SET=$RABBITMQ_EVENTS_CHATS_SET \
    RABBITMQ_EVENTS_CHATS_UPSERT=$RABBITMQ_EVENTS_CHATS_UPSERT \
    RABBITMQ_EVENTS_CHATS_UPDATE=$RABBITMQ_EVENTS_CHATS_UPDATE \
    RABBITMQ_EVENTS_CHATS_DELETE=$RABBITMQ_EVENTS_CHATS_DELETE \
    RABBITMQ_EVENTS_CONNECTION_UPDATE=$RABBITMQ_EVENTS_CONNECTION_UPDATE \
    RABBITMQ_EVENTS_SEND_MESSAGE=$RABBITMQ_EVENTS_SEND_MESSAGE \
    RABBITMQ_EVENTS_INSTANCE_CREATE=$RABBITMQ_EVENTS_INSTANCE_CREATE \
    RABBITMQ_EVENTS_INSTANCE_DELETE=$RABBITMQ_EVENTS_INSTANCE_DELETE \
    RABBITMQ_EVENTS_QRCODE_UPDATED=$RABBITMQ_EVENTS_QRCODE_UPDATED \
    RABBITMQ_EVENTS_GROUPS_UPDATE=$RABBITMQ_EVENTS_GROUPS_UPDATE \
    RABBITMQ_EVENTS_GROUPS_UPSERT=$RABBITMQ_EVENTS_GROUPS_UPSERT \
    RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE=$RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE
COPY ./runWithProvider.js ./
COPY ./tsup.config.ts ./

COPY ./Docker ./Docker

RUN chmod +x ./Docker/scripts/* && dos2unix ./Docker/scripts/*

RUN ./Docker/scripts/generate_database.sh

RUN npm run build

FROM node:20-alpine AS final

RUN apk update && \
    apk add tzdata bash openssl

ENV TZ=America/Sao_Paulo

WORKDIR /evolution

COPY --from=builder /evolution/package.json ./package.json
COPY --from=builder /evolution/package-lock.json ./package-lock.json

COPY --from=builder /evolution/node_modules ./node_modules
COPY --from=builder /evolution/dist ./dist
COPY --from=builder /evolution/prisma ./prisma
COPY --from=builder /evolution/public ./public
ARG SERVER_URL
ARG DATABASE_ENABLED
ARG DATABASE_PROVIDER=postgresql
ARG DATABASE_CONNECTION_URI
ARG DATABASE_CONNECTION_CLIENT_NAME
ARG CACHE_REDIS_ENABLED
ARG CACHE_REDIS_URI
ARG AUTHENTICATION_API_KEY
ARG CONFIG_SESSION_PHONE_VERSION
ARG S3_ENABLED
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG S3_BUCKET
ARG S3_PORT
ARG S3_REGION
ARG S3_ENDPOINT
ARG S3_USE_SSL
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG RABBITMQ_URI
ARG DATABASE_SAVE_DATA_NEW_MESSAGE
ARG DATABASE_SAVE_MESSAGE_UPDATE
ARG DATABASE_SAVE_DATA_CONTACTS
ARG DATABASE_SAVE_DATA_CHATS
ARG DATABASE_SAVE_DATA_HISTORIC
ARG RABBITMQ_ENABLED
ARG RABBITMQ_EXCHANGE_NAME
ARG RABBITMQ_GLOBAL_ENABLED
ARG RABBITMQ_EVENTS_MESSAGES_SET
ARG RABBITMQ_EVENTS_MESSAGES_UPSERT
ARG RABBITMQ_EVENTS_MESSAGES_UPDATE
ARG RABBITMQ_EVENTS_CHATS_SET
ARG RABBITMQ_EVENTS_CHATS_UPSERT
ARG RABBITMQ_EVENTS_CHATS_UPDATE
ARG RABBITMQ_EVENTS_CHATS_DELETE
ARG RABBITMQ_EVENTS_CONNECTION_UPDATE
ARG RABBITMQ_EVENTS_SEND_MESSAGE
ARG RABBITMQ_EVENTS_GROUPS_UPSERT
ARG RABBITMQ_EVENTS_INSTANCE_CREATE
ARG RABBITMQ_EVENTS_INSTANCE_DELETE
ARG RABBITMQ_EVENTS_QRCODE_UPDATED
ARG RABBITMQ_EVENTS_GROUPS_UPDATE
ARG RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE

ENV SERVER_URL=$SERVER_URL \
    DATABASE_ENABLED=$DATABASE_ENABLED \
    DATABASE_PROVIDER=${DATABASE_PROVIDER:-postgresql} \
    DATABASE_CONNECTION_URI=$DATABASE_CONNECTION_URI \
    DATABASE_CONNECTION_CLIENT_NAME=$DATABASE_CONNECTION_CLIENT_NAME \
    CACHE_REDIS_ENABLED=$CACHE_REDIS_ENABLED \
    CACHE_REDIS_URI=$CACHE_REDIS_URI \
    AUTHENTICATION_API_KEY=$AUTHENTICATION_API_KEY \
    CONFIG_SESSION_PHONE_VERSION=$CONFIG_SESSION_PHONE_VERSION \
    S3_ENABLED=$S3_ENABLED \
    S3_ACCESS_KEY=$S3_ACCESS_KEY \
    S3_SECRET_KEY=$S3_SECRET_KEY \
    S3_BUCKET=$S3_BUCKET \
    S3_PORT=$S3_PORT \
    S3_REGION=$S3_REGION \
    S3_ENDPOINT=$S3_ENDPOINT \
    S3_USE_SSL=$S3_USE_SSL \
    POSTGRES_USER=$POSTGRES_USER \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_DB=$POSTGRES_DB \
    RABBITMQ_URI=$RABBITMQ_URI \
    DATABASE_SAVE_DATA_NEW_MESSAGE=$DATABASE_SAVE_DATA_NEW_MESSAGE \
    DATABASE_SAVE_MESSAGE_UPDATE=$DATABASE_SAVE_MESSAGE_UPDATE \
    DATABASE_SAVE_DATA_CONTACTS=$DATABASE_SAVE_DATA_CONTACTS \
    DATABASE_SAVE_DATA_CHATS=$DATABASE_SAVE_DATA_CHATS \
    DATABASE_SAVE_DATA_HISTORIC=$DATABASE_SAVE_DATA_HISTORIC \
    RABBITMQ_ENABLED=$RABBITMQ_ENABLED \
    RABBITMQ_EXCHANGE_NAME=$RABBITMQ_EXCHANGE_NAME \
    RABBITMQ_GLOBAL_ENABLED=$RABBITMQ_GLOBAL_ENABLED \
    RABBITMQ_EVENTS_CHATS_SET=$RABBITMQ_EVENTS_CHATS_SET \
    RABBITMQ_EVENTS_CHATS_UPSERT=$RABBITMQ_EVENTS_CHATS_UPSERT \
    RABBITMQ_EVENTS_CHATS_UPDATE=$RABBITMQ_EVENTS_CHATS_UPDATE \
    RABBITMQ_EVENTS_CHATS_DELETE=$RABBITMQ_EVENTS_CHATS_DELETE \
    RABBITMQ_EVENTS_MESSAGES_SET=$RABBITMQ_EVENTS_MESSAGES_SET \
    RABBITMQ_EVENTS_MESSAGES_UPSERT=$RABBITMQ_EVENTS_MESSAGES_UPSERT \
    RABBITMQ_EVENTS_MESSAGES_UPDATE=$RABBITMQ_EVENTS_MESSAGES_UPDATE \
    RABBITMQ_EVENTS_CONNECTION_UPDATE=$RABBITMQ_EVENTS_CONNECTION_UPDATE \
    RABBITMQ_EVENTS_SEND_MESSAGE=$RABBITMQ_EVENTS_SEND_MESSAGE \
    RABBITMQ_EVENTS_GROUPS_UPSERT=$RABBITMQ_EVENTS_GROUPS_UPSERT \
    RABBITMQ_EVENTS_INSTANCE_CREATE=$RABBITMQ_EVENTS_INSTANCE_CREATE \
    RABBITMQ_EVENTS_INSTANCE_DELETE=$RABBITMQ_EVENTS_INSTANCE_DELETE \
    RABBITMQ_EVENTS_QRCODE_UPDATED=$RABBITMQ_EVENTS_QRCODE_UPDATED \
    RABBITMQ_EVENTS_GROUPS_UPDATE=$RABBITMQ_EVENTS_GROUPS_UPDATE \
    RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE=$RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE

COPY --from=builder /evolution/Docker ./Docker
COPY --from=builder /evolution/runWithProvider.js ./runWithProvider.js
COPY --from=builder /evolution/tsup.config.ts ./tsup.config.ts

ENV DOCKER_ENV=true

EXPOSE 8080

ENTRYPOINT ["/bin/bash", "-c", ". ./Docker/scripts/deploy_database.sh && npm run start:prod" ]